# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Immutable lazy-export inventory for the dashboard facade."""
from __future__ import annotations

from orchestrator._compat_exports import export_group


def _identity_exports(*names: str) -> tuple[tuple[str, str], ...]:
    return tuple(zip(names, names))


EXPORTS = (
    *export_group("orchestrator.analytics", (("analytics", None),)),
    *export_group("orchestrator.analytics.read", (("analytics_read", None),)),
    *export_group(
        "orchestrator.analytics.read",
        _identity_exports(
            "CostCoverageRow",
            "DataExtent",
            "IssueSummaryRow",
            "SkillAdoptionRow",
            "SkillTriggerMatrixRow",
            "SkillTriggerRateRow",
            "Summary",
        ),
    ),
    *export_group(
        "orchestrator.dashboard_state",
        _identity_exports(
            "DASHBOARD_PARALLEL_READS",
            "DEFAULT_PRESET",
            "DEFAULT_TZ_OFFSET_HOURS",
            "DEFAULT_WINDOW_DAYS",
            "DateWindow",
            "PARALLEL_READS_ENV",
            "PARALLEL_READS_MAX_WORKERS",
            "PRESET_3D",
            "PRESET_7D",
            "PRESET_ALL",
            "PRESET_CUSTOM",
            "PRESET_DAYS",
            "PRESET_INLINE_LABELS",
            "PRESET_LABELS",
            "PRESET_OPTIONS",
            "PRESET_RECENT_THREE_DAYS",
            "PRESET_RECENT_WEEK",
            "TZ_OFFSET_OPTIONS",
            "UNCONFIGURED_DB_MESSAGE",
            "_TRUTHY",
            "_extent_dates",
            "_fan_out_reads",
            "_parse_parallel_reads_flag",
            "cache_key",
            "dashboard_parallel_reads_enabled",
            "db_unconfigured_message",
            "default_date_range",
            "format_tz_offset",
            "parse_issue_number",
            "preset_window",
            "previous_window",
            "resolve_stage_filter",
            "shift_ts",
            "to_window",
        ),
    ),
    *export_group(
        "orchestrator.dashboard_kpis",
        _identity_exports(
            "DEFAULT_EXPENSIVE_LIMIT",
            "FAILURE_RATE_BANNER_THRESHOLD",
            "REWORK_BUCKETS",
            "UNPRICED_COST_SOURCES",
            "UNPRICED_COVERAGE_THRESHOLD",
            "InsightBanner",
            "compute_insights",
            "kpi_delta",
            "reliability_tile_data",
            "rework_totals",
            "top_expensive_issues",
        ),
    ),
    *export_group(
        "orchestrator.dashboard_cards",
        _identity_exports(
            "_backend_efficiency_card_html",
            "_card_header_html",
            "_cost_coverage_bar_html",
            "_insights_html",
            "_reliability_tiles_html",
        ),
    ),
    *export_group(
        "orchestrator.dashboard_html",
        _identity_exports(
            "_delta_pill",
            "_filter_meta_html",
            "_issues_table_html",
            "_kpi_strip_html",
            "_skill_triggers_html",
            "_sparkline_svg",
            "_topbar_html",
        ),
    ),
    *export_group(
        "orchestrator.dashboard_skill_adoption",
        (
            ("_skill_adoption_html", "_skill_adoption_html"),
            ("parse_skill_adoption_sort", "parse_skill_adoption_sort"),
        ),
    ),
    *export_group(
        "orchestrator.dashboard_skill_matrix",
        (
            ("_skill_matrix_html", "_skill_matrix_html"),
            ("parse_skill_matrix_sort", "parse_skill_matrix_sort"),
        ),
    ),
    *export_group(
        "orchestrator.dashboard_reads",
        _identity_exports(
            "DEFAULT_RECENT_AGENT_EXITS",
            "LOADING_INDICATOR_MESSAGE",
            "STATIC_METADATA_TTL_SECONDS",
            "_DashboardReadPlan",
            "_build_read_keys",
            "_dispatch_reads",
            "_filter_list",
            "_first_wave_readers",
            "_log_dashboard_load",
            "_read_filter_kwargs",
            "_read_filtered",
            "_run_read_waves",
            "_read_backend_daily_tokens",
            "_read_backend_efficiency",
            "_read_cost_coverage",
            "_read_data_extent",
            "_read_filter_options",
            "_read_hourly_heatmap",
            "_read_prev_kpi",
            "_read_recent_agent_exits",
            "_read_repo_breakdown",
            "_read_review_round",
            "_read_skill_adoption",
            "_read_skill_trigger_matrix",
            "_read_skill_trigger_rates",
            "_read_stage_breakdown",
            "_read_static_metadata",
            "_read_summary",
            "_read_throughput",
            "_read_time_series",
            "_read_top_cost_issues",
            "_scoped_read",
            "_second_wave_readers",
            "_widget_readers",
            "_widget_task",
        ),
    ),
    *export_group(
        "orchestrator.dashboard_kpi_strip",
        (
            ("_KpiInputs", "_KpiInputs"),
            ("_build_kpi_strip_data", "_build_kpi_strip_data"),
        ),
    ),
    *export_group(
        "orchestrator.dashboard_widgets",
        _identity_exports(
            "EMPTY_WINDOW_MESSAGE",
            "NO_DATA_MESSAGE",
            "PLOTLY_CONFIG",
            "_DashboardControls",
            "_DashboardFilters",
            "_DashboardModules",
            "_DashboardPage",
            "_backend_tokens_by_day",
            "_load_dashboard_data",
            "_render_activity_heatmap",
            "_render_chart_widgets",
            "_render_dashboard_footer",
            "_render_dashboard_widgets",
            "_render_drilldown_view",
            "_render_empty_window",
            "_render_first_wave",
            "_render_hero_usage",
            "_render_issues_and_backends",
            "_render_no_data",
            "_render_recent_runs",
            "_render_remaining_widgets",
            "_render_repo_and_reliability",
            "_render_skill_adoption",
            "_render_skill_invocation_diagnostics",
            "_render_skill_matrix_expander",
            "_render_skill_triggers",
            "_render_stage_review_bars",
            "_render_topbar_and_meta",
        ),
    ),
    *export_group(
        "orchestrator._dashboard_runtime",
        _identity_exports(
            "main",
            "_load_dashboard_modules",
            "_configure_dashboard",
            "_stop_if_dashboard_unconfigured",
            "_run_dashboard",
            "_render_dashboard",
        ),
    ),
    *export_group(
        "orchestrator._dashboard_page_controls",
        _identity_exports(
            "_SidebarSelections",
            "_timezone_choice",
            "_resolve_dashboard_filters",
            "_render_dashboard_controls",
            "_prepare_dashboard_page",
            "_render_sidebar_filters",
        ),
    ),
    *export_group(
        "orchestrator._dashboard_date_widgets",
        _identity_exports(
            "_DateFilterColumns",
            "_date_filter_columns",
            "_render_date_filter_label",
            "_preset_radio_index",
            "_render_preset_choice",
        ),
    ),
    *export_group(
        "orchestrator._dashboard_date_range",
        _identity_exports(
            "_initial_filter_window",
            "_render_date_inputs",
            "_render_date_filter_bar",
        ),
    ),
    *export_group(
        "orchestrator._dashboard_drilldown",
        (("_render_drilldown", "_render_drilldown"),),
    ),
)

EXPORTED_NAMES = tuple(sorted(target.export_name for target in EXPORTS))
