# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Immutable lazy-export inventory for :mod:`orchestrator.worktrees`."""

from __future__ import annotations

from orchestrator._compat_exports import export_group

EXPORTS = (
    *export_group(
        "logging",
        (("logging", None),),
    ),
    *export_group(
        "orchestrator.base_sync",
        (
            ("_AUTO_REBASE_PARK_REASONS", "_AUTO_REBASE_PARK_REASONS"),
            ("_PR_REFRESH_DETOUR_LABELS", "_PR_REFRESH_DETOUR_LABELS"),
            ("_merge_base_into_worktree", "_merge_base_into_worktree"),
            ("_park_auto_rebase_failure", "_park_auto_rebase_failure"),
            ("_rebase_base_into_worktree", "_rebase_base_into_worktree"),
            ("_rebase_in_progress", "_rebase_in_progress"),
            ("_recover_pending_auto_base_rebase", "_recover_pending_auto_base_rebase"),
            ("_refresh_base_and_worktrees", "_refresh_base_and_worktrees"),
            ("_route_pr_worktree_to_resolving_conflict", "_route_pr_worktree_to_resolving_conflict"),
            ("_sync_pr_worktree_to_base", "_sync_pr_worktree_to_base"),
            ("_sync_worktree_with_base", "_sync_worktree_with_base"),
        ),
    ),
    *export_group(
        "orchestrator.branch_publication",
        (
            ("_CONVENTIONAL_RE", "_CONVENTIONAL_RE"),
            ("_branch_ahead_behind", "_branch_ahead_behind"),
            ("_first_commit_subject", "_first_commit_subject"),
            ("_infer_subject_prefix", "_infer_subject_prefix"),
            ("_is_conventional_subject", "_is_conventional_subject"),
            ("_is_prefixed_subject", "_is_prefixed_subject"),
            ("_pr_title_from_commit_or_issue", "_pr_title_from_commit_or_issue"),
            ("_recent_base_subjects", "_recent_base_subjects"),
            ("_squash_and_force_push", "_squash_and_force_push"),
        ),
    ),
    *export_group(
        "orchestrator.git_plumbing",
        (
            ("_GIT_NO_PROMPT_ENV", "_GIT_NO_PROMPT_ENV"),
            ("_TARGET_ROOT_LOCKS", "_TARGET_ROOT_LOCKS"),
            ("_TARGET_ROOT_LOCKS_LOCK", "_TARGET_ROOT_LOCKS_LOCK"),
            ("_authed_fetch", "_authed_fetch"),
            ("_authed_target_fetch", "_authed_target_fetch"),
            ("_git", "_git"),
            ("_git_hardened", "_git_hardened"),
            ("_push_branch", "_push_branch"),
            ("_target_root_lock", "_target_root_lock"),
        ),
    ),
    *export_group(
        "orchestrator.verify",
        (
            ("VerifyResult", "VerifyResult"),
            ("_head_sha", "_head_sha"),
            ("_run_verify_commands", "_run_verify_commands"),
            ("_truncate_verify_output", "_truncate_verify_output"),
            ("_worktree_dirty_files", "_worktree_dirty_files"),
        ),
    ),
    *export_group(
        "orchestrator.worktree_lifecycle",
        (
            ("_SLUG_SAFE_RE", "_SLUG_SAFE_RE"),
            ("_branch_has_unpushed_commits", "_branch_has_unpushed_commits"),
            ("_branch_name", "_branch_name"),
            ("_cleanup_decompose_worktree", "_cleanup_decompose_worktree"),
            ("_cleanup_question_worktree", "_cleanup_question_worktree"),
            ("_cleanup_terminal_branch", "_cleanup_terminal_branch"),
            ("_decompose_worktree_path", "_decompose_worktree_path"),
            ("_ensure_decompose_worktree", "_ensure_decompose_worktree"),
            ("_ensure_pr_worktree", "_ensure_pr_worktree"),
            ("_ensure_worktree", "_ensure_worktree"),
            ("_has_new_commits", "_has_new_commits"),
            ("_repo_worktrees_root", "_repo_worktrees_root"),
            ("_resolve_branch_name", "_resolve_branch_name"),
            ("_sanitize_branch_segment", "_sanitize_branch_segment"),
            ("_sanitize_slug", "_sanitize_slug"),
            ("_worktree_path", "_worktree_path"),
        ),
    ),
)
EXPORTED_NAMES = (
    "VerifyResult",
    "_AUTO_REBASE_PARK_REASONS",
    "_CONVENTIONAL_RE",
    "_GIT_NO_PROMPT_ENV",
    "_PR_REFRESH_DETOUR_LABELS",
    "_SLUG_SAFE_RE",
    "_TARGET_ROOT_LOCKS",
    "_TARGET_ROOT_LOCKS_LOCK",
    "_authed_fetch",
    "_authed_target_fetch",
    "_branch_ahead_behind",
    "_branch_has_unpushed_commits",
    "_branch_name",
    "_cleanup_decompose_worktree",
    "_cleanup_question_worktree",
    "_cleanup_terminal_branch",
    "_decompose_worktree_path",
    "_ensure_decompose_worktree",
    "_ensure_pr_worktree",
    "_ensure_worktree",
    "_first_commit_subject",
    "_git",
    "_git_hardened",
    "_has_new_commits",
    "_head_sha",
    "_infer_subject_prefix",
    "_is_conventional_subject",
    "_is_prefixed_subject",
    "_merge_base_into_worktree",
    "_park_auto_rebase_failure",
    "_pr_title_from_commit_or_issue",
    "_push_branch",
    "_rebase_base_into_worktree",
    "_rebase_in_progress",
    "_recent_base_subjects",
    "_recover_pending_auto_base_rebase",
    "_refresh_base_and_worktrees",
    "_repo_worktrees_root",
    "_resolve_branch_name",
    "_route_pr_worktree_to_resolving_conflict",
    "_run_verify_commands",
    "_sanitize_branch_segment",
    "_sanitize_slug",
    "_squash_and_force_push",
    "_sync_pr_worktree_to_base",
    "_sync_worktree_with_base",
    "_target_root_lock",
    "_truncate_verify_output",
    "_worktree_dirty_files",
    "_worktree_path",
)
