# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Immutable lazy-export inventory for :mod:`orchestrator.workflow`."""

from __future__ import annotations

from orchestrator._compat_exports import export_group

EXPORTS = (
    *export_group(
        "concurrent.futures",
        (
            ("ThreadPoolExecutor", "ThreadPoolExecutor"),
            ("as_completed", "as_completed"),
        ),
    ),
    *export_group(
        "contextlib",
        (("contextlib", None),),
    ),
    *export_group(
        "dataclasses",
        (
            ("dataclass", "dataclass"),
            ("field", "field"),
        ),
    ),
    *export_group(
        "datetime",
        (
            ("datetime", "datetime"),
            ("timezone", "timezone"),
        ),
    ),
    *export_group(
        "functools",
        (("functools", None),),
    ),
    *export_group(
        "github.Issue",
        (("Issue", "Issue"),),
    ),
    *export_group(
        "logging",
        (("logging", None),),
    ),
    *export_group(
        "orchestrator._workflow_dependencies",
        (
            ("analytics", "analytics"),
            ("config", "config"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_agent_runs",
        (
            ("_AgentRunRequest", "_AgentRunRequest"),
            ("_agent_run_kwargs", "_agent_run_kwargs"),
            ("_configured_model", "_configured_model"),
            ("_emit_triggered_skills", "_emit_triggered_skills"),
            ("_now_iso", "_now_iso"),
            ("_record_tracked_agent_exit", "_record_tracked_agent_exit"),
            ("_run_agent_tracked", "_run_agent_tracked"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_community",
        (
            ("_CommunityContribution", "_CommunityContribution"),
            ("_community_contribution_for_pr", "_community_contribution_for_pr"),
            ("_label_community_contribution", "_label_community_contribution"),
            ("_sweep_community_contribution_prs", "_sweep_community_contribution_prs"),
            ("_sweep_pr_contribution", "_sweep_pr_contribution"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_dispatch",
        (
            ("_process_issue", "_process_issue"),
            ("_route_issue_to_handler", "_route_issue_to_handler"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_partition",
        (
            ("_PollablePartition", "_PollablePartition"),
            ("_PollablePartitionBuilder", "_PollablePartitionBuilder"),
            ("_classify_pollable_issue", "_classify_pollable_issue"),
            ("_family_bucket_cap_exempt", "_family_bucket_cap_exempt"),
            ("_partition_pollable_issues", "_partition_pollable_issues"),
            ("_read_issue_routing", "_read_issue_routing"),
            ("_refetch_and_process", "_refetch_and_process"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_pickup",
        (
            ("_handle_pickup", "_handle_pickup"),
            ("_pickup_author_allowed", "_pickup_author_allowed"),
            ("_record_pickup_comment", "_record_pickup_comment"),
            ("_start_decomposing", "_start_decomposing"),
            ("_start_implementing", "_start_implementing"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_run_guards",
        (
            ("_ignore_if_interrupted", "_ignore_if_interrupted"),
            ("_park_awaiting_human", "_park_awaiting_human"),
            ("_paused_during_agent_run", "_paused_during_agent_run"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_scheduler",
        (
            ("_dispatch_via_scheduler", "_dispatch_via_scheduler"),
            ("_drain_scheduler_family_bucket", "_drain_scheduler_family_bucket"),
            ("_issue_is_closed", "_issue_is_closed"),
            ("_scheduler_per_repo_cap", "_scheduler_per_repo_cap"),
            ("_submit_scheduler_family_bucket", "_submit_scheduler_family_bucket"),
            ("_submit_scheduler_fanout_issues", "_submit_scheduler_fanout_issues"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_state",
        (
            ("_CAP_EXEMPT_FAMILY_LABELS", "_CAP_EXEMPT_FAMILY_LABELS"),
            ("_FAMILY_AWARE_LABELS", "_FAMILY_AWARE_LABELS"),
            ("_FAMILY_BUCKET_ISSUE", "_FAMILY_BUCKET_ISSUE"),
            ("_ISSUE_HANDLER_NAMES", "_ISSUE_HANDLER_NAMES"),
            ("_ISSUE_STATE_CLOSED", "_ISSUE_STATE_CLOSED"),
            ("_ISSUE_STATE_OPEN", "_ISSUE_STATE_OPEN"),
            ("_PROCESSING_FAILED_LOG", "_PROCESSING_FAILED_LOG"),
            ("_STATE_ATTR", "_STATE_ATTR"),
            ("log", "log"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_terminal_actions",
        (
            ("_ReviewTerminalContext", "_ReviewTerminalContext"),
            ("_cleanup_review_terminal", "_cleanup_review_terminal"),
            ("_close_terminal_issue", "_close_terminal_issue"),
            ("_finalize_closed_issue_with_open_pr", "_finalize_closed_issue_with_open_pr"),
            ("_finalize_if_pr_merged", "_finalize_if_pr_merged"),
            ("_finalize_merged_pr", "_finalize_merged_pr"),
            ("_finalize_rejected_pr", "_finalize_rejected_pr"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_terminals",
        (
            ("_ClosedIssuePR", "_ClosedIssuePR"),
            ("_closed_issue_pr", "_closed_issue_pr"),
            ("_drain_review_pr_terminals", "_drain_review_pr_terminals"),
            ("_drain_review_terminal", "_drain_review_terminal"),
            ("_emit_closed_pr_rejection", "_emit_closed_pr_rejection"),
            ("_finalize_if_issue_closed", "_finalize_if_issue_closed"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_tick",
        (
            ("_ParallelTickPlan", "_ParallelTickPlan"),
            ("_drain_family_bucket", "_drain_family_bucket"),
            ("_drain_parallel_futures", "_drain_parallel_futures"),
            ("_run_parallel_tick", "_run_parallel_tick"),
            ("_run_sequential_tick", "_run_sequential_tick"),
            ("tick", "tick"),
        ),
    ),
    *export_group(
        "orchestrator._workflow_usage",
        (
            ("_accumulate_issue_usage", "_accumulate_issue_usage"),
            ("_format_issue_usage_verdict", "_format_issue_usage_verdict"),
            ("_post_issue_usage_verdict", "_post_issue_usage_verdict"),
        ),
    ),
    *export_group(
        "orchestrator.agents",
        (
            ("AgentResult", "AgentResult"),
            ("run_agent", "run_agent"),
        ),
    ),
    *export_group(
        "orchestrator.base_sync",
        (
            ("_AUTO_REBASE_PARK_REASONS", "_AUTO_REBASE_PARK_REASONS"),
            ("_merge_base_into_worktree", "_merge_base_into_worktree"),
            ("_rebase_base_into_worktree", "_rebase_base_into_worktree"),
            ("_rebase_in_progress", "_rebase_in_progress"),
            ("_refresh_base_and_worktrees", "_refresh_base_and_worktrees"),
            ("_sync_pr_worktree_to_base", "_sync_pr_worktree_to_base"),
            ("_sync_worktree_with_base", "_sync_worktree_with_base"),
        ),
    ),
    *export_group(
        "orchestrator.github",
        (
            ("COMMUNITY_CONTRIBUTION_LABEL", "COMMUNITY_CONTRIBUTION_LABEL"),
            ("GitHubClient", "GitHubClient"),
            ("PinnedState", "PinnedState"),
            ("hard_skip_control_label", "hard_skip_control_label"),
        ),
    ),
    *export_group(
        "orchestrator.scheduler",
        (("IssueScheduler", "IssueScheduler"),),
    ),
    *export_group(
        "orchestrator.skill_catalog",
        (("_emit_repo_skill_catalog", "_emit_repo_skill_catalog"),),
    ),
    *export_group(
        "orchestrator.stages.conflicts",
        (("_handle_resolving_conflict", "_handle_resolving_conflict"),),
    ),
    *export_group(
        "orchestrator.stages.decomposition",
        (
            ("_handle_blocked", "_handle_blocked"),
            ("_handle_decomposing", "_handle_decomposing"),
            ("_handle_ready", "_handle_ready"),
            ("_handle_umbrella", "_handle_umbrella"),
            ("_read_decomposer_session", "_read_decomposer_session"),
        ),
    ),
    *export_group(
        "orchestrator.stages.documenting",
        (("_handle_documenting", "_handle_documenting"),),
    ),
    *export_group(
        "orchestrator.stages.fixing",
        (("_handle_fixing", "_handle_fixing"),),
    ),
    *export_group(
        "orchestrator.stages.implementing",
        (
            ("_SILENT_PARKS_BEFORE_FRESH_SESSION", "_SILENT_PARKS_BEFORE_FRESH_SESSION"),
            ("_check_and_increment_retry_budget", "_check_and_increment_retry_budget"),
            ("_drop_poisoned_dev_session", "_drop_poisoned_dev_session"),
            ("_handle_implementing", "_handle_implementing"),
            ("_is_context_overflow_failure", "_is_context_overflow_failure"),
            ("_is_poisoned_session_failure", "_is_poisoned_session_failure"),
            ("_is_session_limit_message", "_is_session_limit_message"),
            ("_is_stale_session_failure", "_is_stale_session_failure"),
            ("_on_dirty_worktree", "_on_dirty_worktree"),
            ("_on_question", "_on_question"),
            ("_read_dev_session", "_read_dev_session"),
            ("_resume_dev_with_text", "_resume_dev_with_text"),
            ("_resume_developer_on_human_reply", "_resume_developer_on_human_reply"),
        ),
    ),
    *export_group(
        "orchestrator.stages.in_review",
        (
            ("_comment_created_at", "_comment_created_at"),
            ("_handle_in_review", "_handle_in_review"),
        ),
    ),
    *export_group(
        "orchestrator.stages.question",
        (("_handle_question", "_handle_question"),),
    ),
    *export_group(
        "orchestrator.stages.validating",
        (
            ("_VALIDATING_TRANSIENT_PARK_REASONS", "_VALIDATING_TRANSIENT_PARK_REASONS"),
            ("_handle_dev_fix_result", "_handle_dev_fix_result"),
            ("_handle_validating", "_handle_validating"),
            ("_latest_pr_comment_ids", "_latest_pr_comment_ids"),
            ("_post_user_content_change_result", "_post_user_content_change_result"),
            ("_stranded_fix_unpushed", "_stranded_fix_unpushed"),
            ("_try_recover_validating_transient_park", "_try_recover_validating_transient_park"),
        ),
    ),
    *export_group(
        "orchestrator.state_machine",
        (("WorkflowLabel", "WorkflowLabel"),),
    ),
    *export_group(
        "orchestrator.usage",
        (("UsageMetrics", "UsageMetrics"),),
    ),
    *export_group(
        "orchestrator.workflow_drift",
        (
            ("_build_user_content_change_prompt", "_build_user_content_change_prompt"),
            ("_compute_user_content_hash", "_compute_user_content_hash"),
            ("_detect_user_content_change", "_detect_user_content_change"),
            ("_mark_drift_comments_consumed", "_mark_drift_comments_consumed"),
            ("_route_drift_to_decomposing", "_route_drift_to_decomposing"),
        ),
    ),
    *export_group(
        "orchestrator.workflow_messages",
        (
            ("_CONTINUE_PARK_REASONS", "_CONTINUE_PARK_REASONS"),
            ("_CONTINUE_RETRY_PROMPT", "_CONTINUE_RETRY_PROMPT"),
            ("_FOREGROUND_ONLY_NOTE", "_FOREGROUND_ONLY_NOTE"),
            ("_MANIFEST_RE", "_MANIFEST_RE"),
            ("_ORCH_COMMENT_MARKER", "_ORCH_COMMENT_MARKER"),
            ("_STDERR_TAIL_BUDGET", "_STDERR_TAIL_BUDGET"),
            ("_as_blockquote", "_as_blockquote"),
            ("_build_conflict_resolution_prompt", "_build_conflict_resolution_prompt"),
            ("_build_decompose_prompt", "_build_decompose_prompt"),
            ("_build_documentation_prompt", "_build_documentation_prompt"),
            ("_build_fix_prompt", "_build_fix_prompt"),
            ("_build_fresh_respawn_preamble", "_build_fresh_respawn_preamble"),
            ("_build_implement_prompt", "_build_implement_prompt"),
            ("_build_pr_comment_followup", "_build_pr_comment_followup"),
            ("_build_question_followup_prompt", "_build_question_followup_prompt"),
            ("_build_question_prompt", "_build_question_prompt"),
            ("_build_review_prompt", "_build_review_prompt"),
            ("_build_single_decision_comment", "_build_single_decision_comment"),
            ("_build_tracked_repos_context", "_build_tracked_repos_context"),
            ("_continue_command_action", "_continue_command_action"),
            ("_drift_ack_reason", "_drift_ack_reason"),
            ("_format_stderr_diagnostics", "_format_stderr_diagnostics"),
            ("_is_bare_orchestrator_continue", "_is_bare_orchestrator_continue"),
            ("_orchestrator_ids", "_orchestrator_ids"),
            ("_parse_documentation_verdict", "_parse_documentation_verdict"),
            ("_parse_manifest", "_parse_manifest"),
            ("_parse_orchestrator_continue", "_parse_orchestrator_continue"),
            ("_parse_review_verdict", "_parse_review_verdict"),
            ("_post_issue_comment", "_post_issue_comment"),
            ("_post_pr_comment", "_post_pr_comment"),
            ("_quote_comment_line", "_quote_comment_line"),
            ("_recent_comments_text", "_recent_comments_text"),
            ("_redact_secrets", "_redact_secrets"),
            ("_refuse_parked_continue", "_refuse_parked_continue"),
            ("_stderr_log_tail", "_stderr_log_tail"),
            ("_with_orch_marker", "_with_orch_marker"),
        ),
    ),
    *export_group(
        "orchestrator.worktrees",
        (
            ("_authed_fetch", "_authed_fetch"),
            ("_authed_target_fetch", "_authed_target_fetch"),
            ("_branch_ahead_behind", "_branch_ahead_behind"),
            ("_branch_has_unpushed_commits", "_branch_has_unpushed_commits"),
            ("_branch_name", "_branch_name"),
            ("_cleanup_decompose_worktree", "_cleanup_decompose_worktree"),
            ("_cleanup_question_worktree", "_cleanup_question_worktree"),
            ("_cleanup_terminal_branch", "_cleanup_terminal_branch"),
            ("_decompose_worktree_path", "_decompose_worktree_path"),
            ("_ensure_decompose_worktree", "_ensure_decompose_worktree"),
            ("_ensure_pr_worktree", "_ensure_pr_worktree"),
            ("_ensure_worktree", "_ensure_worktree"),
            ("_first_commit_subject", "_first_commit_subject"),
            ("_git", "_git"),
            ("_git_hardened", "_git_hardened"),
            ("_has_new_commits", "_has_new_commits"),
            ("_head_sha", "_head_sha"),
            ("_infer_subject_prefix", "_infer_subject_prefix"),
            ("_is_conventional_subject", "_is_conventional_subject"),
            ("_is_prefixed_subject", "_is_prefixed_subject"),
            ("_pr_title_from_commit_or_issue", "_pr_title_from_commit_or_issue"),
            ("_push_branch", "_push_branch"),
            ("_resolve_branch_name", "_resolve_branch_name"),
            ("_run_verify_commands", "_run_verify_commands"),
            ("_sanitize_branch_segment", "_sanitize_branch_segment"),
            ("_sanitize_slug", "_sanitize_slug"),
            ("_squash_and_force_push", "_squash_and_force_push"),
            ("_worktree_dirty_files", "_worktree_dirty_files"),
            ("_worktree_path", "_worktree_path"),
        ),
    ),
    *export_group(
        "pathlib",
        (("Path", "Path"),),
    ),
    *export_group(
        "subprocess",
        (("subprocess", None),),
    ),
    *export_group(
        "sys",
        (("sys", None),),
    ),
    *export_group(
        "threading",
        (("threading", None),),
    ),
    *export_group(
        "time",
        (("time", None),),
    ),
    *export_group(
        "types",
        (("MappingProxyType", "MappingProxyType"),),
    ),
    *export_group(
        "typing",
        (
            ("Any", "Any"),
            ("Mapping", "Mapping"),
            ("Optional", "Optional"),
        ),
    ),
)
EXPORTED_NAMES = (
    "_AUTO_REBASE_PARK_REASONS",
    "_CAP_EXEMPT_FAMILY_LABELS",
    "_CONTINUE_PARK_REASONS",
    "_CONTINUE_RETRY_PROMPT",
    "_FAMILY_AWARE_LABELS",
    "_FAMILY_BUCKET_ISSUE",
    "_FOREGROUND_ONLY_NOTE",
    "_MANIFEST_RE",
    "_ORCH_COMMENT_MARKER",
    "_PollablePartition",
    "_SILENT_PARKS_BEFORE_FRESH_SESSION",
    "_STDERR_TAIL_BUDGET",
    "_VALIDATING_TRANSIENT_PARK_REASONS",
    "_accumulate_issue_usage",
    "_as_blockquote",
    "_authed_fetch",
    "_authed_target_fetch",
    "_branch_ahead_behind",
    "_branch_has_unpushed_commits",
    "_branch_name",
    "_build_conflict_resolution_prompt",
    "_build_decompose_prompt",
    "_build_documentation_prompt",
    "_build_fix_prompt",
    "_build_fresh_respawn_preamble",
    "_build_implement_prompt",
    "_build_pr_comment_followup",
    "_build_question_followup_prompt",
    "_build_question_prompt",
    "_build_review_prompt",
    "_build_single_decision_comment",
    "_build_tracked_repos_context",
    "_build_user_content_change_prompt",
    "_check_and_increment_retry_budget",
    "_classify_pollable_issue",
    "_cleanup_decompose_worktree",
    "_cleanup_question_worktree",
    "_cleanup_terminal_branch",
    "_comment_created_at",
    "_compute_user_content_hash",
    "_configured_model",
    "_continue_command_action",
    "_decompose_worktree_path",
    "_detect_user_content_change",
    "_dispatch_via_scheduler",
    "_drain_family_bucket",
    "_drain_review_pr_terminals",
    "_drain_scheduler_family_bucket",
    "_drift_ack_reason",
    "_drop_poisoned_dev_session",
    "_emit_repo_skill_catalog",
    "_ensure_decompose_worktree",
    "_ensure_pr_worktree",
    "_ensure_worktree",
    "_family_bucket_cap_exempt",
    "_finalize_if_issue_closed",
    "_finalize_if_pr_merged",
    "_first_commit_subject",
    "_format_issue_usage_verdict",
    "_format_stderr_diagnostics",
    "_git",
    "_git_hardened",
    "_handle_blocked",
    "_handle_decomposing",
    "_handle_dev_fix_result",
    "_handle_documenting",
    "_handle_fixing",
    "_handle_implementing",
    "_handle_in_review",
    "_handle_pickup",
    "_handle_question",
    "_handle_ready",
    "_handle_resolving_conflict",
    "_handle_umbrella",
    "_handle_validating",
    "_has_new_commits",
    "_head_sha",
    "_ignore_if_interrupted",
    "_infer_subject_prefix",
    "_is_bare_orchestrator_continue",
    "_is_context_overflow_failure",
    "_is_conventional_subject",
    "_is_poisoned_session_failure",
    "_is_prefixed_subject",
    "_is_session_limit_message",
    "_is_stale_session_failure",
    "_issue_is_closed",
    "_latest_pr_comment_ids",
    "_mark_drift_comments_consumed",
    "_merge_base_into_worktree",
    "_now_iso",
    "_on_dirty_worktree",
    "_on_question",
    "_orchestrator_ids",
    "_park_awaiting_human",
    "_parse_documentation_verdict",
    "_parse_manifest",
    "_parse_orchestrator_continue",
    "_parse_review_verdict",
    "_partition_pollable_issues",
    "_paused_during_agent_run",
    "_post_issue_comment",
    "_post_issue_usage_verdict",
    "_post_pr_comment",
    "_post_user_content_change_result",
    "_pr_title_from_commit_or_issue",
    "_process_issue",
    "_push_branch",
    "_quote_comment_line",
    "_read_decomposer_session",
    "_read_dev_session",
    "_rebase_base_into_worktree",
    "_rebase_in_progress",
    "_recent_comments_text",
    "_redact_secrets",
    "_refetch_and_process",
    "_refresh_base_and_worktrees",
    "_refuse_parked_continue",
    "_resolve_branch_name",
    "_resume_dev_with_text",
    "_resume_developer_on_human_reply",
    "_route_drift_to_decomposing",
    "_route_issue_to_handler",
    "_run_agent_tracked",
    "_run_parallel_tick",
    "_run_sequential_tick",
    "_run_verify_commands",
    "_sanitize_branch_segment",
    "_sanitize_slug",
    "_squash_and_force_push",
    "_stderr_log_tail",
    "_stranded_fix_unpushed",
    "_sweep_community_contribution_prs",
    "_sync_pr_worktree_to_base",
    "_sync_worktree_with_base",
    "_try_recover_validating_transient_park",
    "_with_orch_marker",
    "_worktree_dirty_files",
    "_worktree_path",
    "subprocess",
    "tick",
)
