# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Static declarations for the lazy dashboard facade."""

from typing import Any

CostCoverageRow: Any
DASHBOARD_PARALLEL_READS: Any
DEFAULT_EXPENSIVE_LIMIT: Any
DEFAULT_PRESET: Any
DEFAULT_RECENT_AGENT_EXITS: Any
DEFAULT_TZ_OFFSET_HOURS: Any
DEFAULT_WINDOW_DAYS: Any
DataExtent: Any
DateWindow: Any
EMPTY_WINDOW_MESSAGE: Any
FAILURE_RATE_BANNER_THRESHOLD: Any
InsightBanner: Any
IssueSummaryRow: Any
LOADING_INDICATOR_MESSAGE: Any
NO_DATA_MESSAGE: Any
PARALLEL_READS_ENV: Any
PARALLEL_READS_MAX_WORKERS: Any
PLOTLY_CONFIG: Any
PRESET_3D: Any
PRESET_7D: Any
PRESET_ALL: Any
PRESET_CUSTOM: Any
PRESET_DAYS: Any
PRESET_INLINE_LABELS: Any
PRESET_LABELS: Any
PRESET_OPTIONS: Any
PRESET_RECENT_THREE_DAYS: Any
PRESET_RECENT_WEEK: Any
REWORK_BUCKETS: Any
STATIC_METADATA_TTL_SECONDS: Any
SkillAdoptionRow: Any
SkillTriggerMatrixRow: Any
SkillTriggerRateRow: Any
Summary: Any
TZ_OFFSET_OPTIONS: Any
UNCONFIGURED_DB_MESSAGE: Any
UNPRICED_COST_SOURCES: Any
UNPRICED_COVERAGE_THRESHOLD: Any
_DashboardControls: Any
_DashboardFilters: Any
_DashboardModules: Any
_DashboardPage: Any
_DashboardReadPlan: Any
_DateFilterColumns: Any
_KpiInputs: Any
_SidebarSelections: Any
_TRUTHY: Any
_backend_efficiency_card_html: Any
_backend_tokens_by_day: Any
_build_kpi_strip_data: Any
_build_read_keys: Any
_card_header_html: Any
_configure_dashboard: Any
_cost_coverage_bar_html: Any
_date_filter_columns: Any
_delta_pill: Any
_dispatch_reads: Any
_extent_dates: Any
_fan_out_reads: Any
_filter_list: Any
_filter_meta_html: Any
_first_wave_readers: Any
_initial_filter_window: Any
_insights_html: Any
_issues_table_html: Any
_kpi_strip_html: Any
_load_dashboard_data: Any
_load_dashboard_modules: Any
_log_dashboard_load: Any
_parse_parallel_reads_flag: Any
_prepare_dashboard_page: Any
_preset_radio_index: Any
_read_backend_daily_tokens: Any
_read_backend_efficiency: Any
_read_cost_coverage: Any
_read_data_extent: Any
_read_filter_kwargs: Any
_read_filter_options: Any
_read_filtered: Any
_read_hourly_heatmap: Any
_read_prev_kpi: Any
_read_recent_agent_exits: Any
_read_repo_breakdown: Any
_read_review_round: Any
_read_skill_adoption: Any
_read_skill_trigger_matrix: Any
_read_skill_trigger_rates: Any
_read_stage_breakdown: Any
_read_static_metadata: Any
_read_summary: Any
_read_throughput: Any
_read_time_series: Any
_read_top_cost_issues: Any
_reliability_tiles_html: Any
_render_activity_heatmap: Any
_render_chart_widgets: Any
_render_dashboard: Any
_render_dashboard_controls: Any
_render_dashboard_footer: Any
_render_dashboard_widgets: Any
_render_date_filter_bar: Any
_render_date_filter_label: Any
_render_date_inputs: Any
_render_drilldown: Any
_render_drilldown_view: Any
_render_empty_window: Any
_render_first_wave: Any
_render_hero_usage: Any
_render_issues_and_backends: Any
_render_no_data: Any
_render_preset_choice: Any
_render_recent_runs: Any
_render_remaining_widgets: Any
_render_repo_and_reliability: Any
_render_sidebar_filters: Any
_render_skill_adoption: Any
_render_skill_invocation_diagnostics: Any
_render_skill_matrix_expander: Any
_render_skill_triggers: Any
_render_stage_review_bars: Any
_render_topbar_and_meta: Any
_resolve_dashboard_filters: Any
_run_dashboard: Any
_run_read_waves: Any
_scoped_read: Any
_second_wave_readers: Any
_skill_adoption_html: Any
_skill_matrix_html: Any
_skill_triggers_html: Any
_sparkline_svg: Any
_stop_if_dashboard_unconfigured: Any
_timezone_choice: Any
_topbar_html: Any
_widget_readers: Any
_widget_task: Any
analytics: Any
analytics_read: Any
cache_key: Any
compute_insights: Any
dashboard_parallel_reads_enabled: Any
db_unconfigured_message: Any
default_date_range: Any
format_tz_offset: Any
kpi_delta: Any
main: Any
parse_issue_number: Any
parse_skill_adoption_sort: Any
parse_skill_matrix_sort: Any
preset_window: Any
previous_window: Any
reliability_tile_data: Any
resolve_stage_filter: Any
rework_totals: Any
shift_ts: Any
to_window: Any
top_expensive_issues: Any
__all__: tuple[str, ...]
