# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Static declarations for the lazy compatibility facade."""

from typing import Any

_AUTO_REBASE_PARK_REASONS: Any
_CAP_EXEMPT_FAMILY_LABELS: Any
_CONTINUE_PARK_REASONS: Any
_CONTINUE_RETRY_PROMPT: Any
_FAMILY_AWARE_LABELS: Any
_FAMILY_BUCKET_ISSUE: Any
_FOREGROUND_ONLY_NOTE: Any
_MANIFEST_RE: Any
_ORCH_COMMENT_MARKER: Any
_PollablePartition: Any
_SILENT_PARKS_BEFORE_FRESH_SESSION: Any
_STDERR_TAIL_BUDGET: Any
_VALIDATING_TRANSIENT_PARK_REASONS: Any
_accumulate_issue_usage: Any
_as_blockquote: Any
_authed_fetch: Any
_authed_target_fetch: Any
_branch_ahead_behind: Any
_branch_has_unpushed_commits: Any
_branch_name: Any
_build_conflict_resolution_prompt: Any
_build_decompose_prompt: Any
_build_documentation_prompt: Any
_build_fix_prompt: Any
_build_fresh_respawn_preamble: Any
_build_implement_prompt: Any
_build_pr_comment_followup: Any
_build_question_followup_prompt: Any
_build_question_prompt: Any
_build_review_prompt: Any
_build_single_decision_comment: Any
_build_tracked_repos_context: Any
_build_user_content_change_prompt: Any
_check_and_increment_retry_budget: Any
_classify_pollable_issue: Any
_cleanup_decompose_worktree: Any
_cleanup_question_worktree: Any
_cleanup_terminal_branch: Any
_comment_created_at: Any
_compute_user_content_hash: Any
_configured_model: Any
_continue_command_action: Any
_decompose_worktree_path: Any
_detect_user_content_change: Any
_dispatch_via_scheduler: Any
_drain_family_bucket: Any
_drain_review_pr_terminals: Any
_drain_scheduler_family_bucket: Any
_drift_ack_reason: Any
_drop_poisoned_dev_session: Any
_emit_repo_skill_catalog: Any
_ensure_decompose_worktree: Any
_ensure_pr_worktree: Any
_ensure_worktree: Any
_family_bucket_cap_exempt: Any
_finalize_if_issue_closed: Any
_finalize_if_pr_merged: Any
_first_commit_subject: Any
_format_issue_usage_verdict: Any
_format_stderr_diagnostics: Any
_git: Any
_git_hardened: Any
_handle_blocked: Any
_handle_decomposing: Any
_handle_dev_fix_result: Any
_handle_documenting: Any
_handle_fixing: Any
_handle_implementing: Any
_handle_in_review: Any
_handle_pickup: Any
_handle_question: Any
_handle_ready: Any
_handle_resolving_conflict: Any
_handle_umbrella: Any
_handle_validating: Any
_has_new_commits: Any
_head_sha: Any
_ignore_if_interrupted: Any
_infer_subject_prefix: Any
_is_bare_orchestrator_continue: Any
_is_context_overflow_failure: Any
_is_conventional_subject: Any
_is_poisoned_session_failure: Any
_is_prefixed_subject: Any
_is_session_limit_message: Any
_is_stale_session_failure: Any
_issue_is_closed: Any
_latest_pr_comment_ids: Any
_mark_drift_comments_consumed: Any
_merge_base_into_worktree: Any
_now_iso: Any
_on_dirty_worktree: Any
_on_question: Any
_orchestrator_ids: Any
_park_awaiting_human: Any
_parse_documentation_verdict: Any
_parse_manifest: Any
_parse_orchestrator_continue: Any
_parse_review_verdict: Any
_partition_pollable_issues: Any
_paused_during_agent_run: Any
_post_issue_comment: Any
_post_issue_usage_verdict: Any
_post_pr_comment: Any
_post_user_content_change_result: Any
_pr_title_from_commit_or_issue: Any
_process_issue: Any
_push_branch: Any
_quote_comment_line: Any
_read_decomposer_session: Any
_read_dev_session: Any
_rebase_base_into_worktree: Any
_rebase_in_progress: Any
_recent_comments_text: Any
_redact_secrets: Any
_refetch_and_process: Any
_refresh_base_and_worktrees: Any
_refuse_parked_continue: Any
_resolve_branch_name: Any
_resume_dev_with_text: Any
_resume_developer_on_human_reply: Any
_route_drift_to_decomposing: Any
_route_issue_to_handler: Any
_run_agent_tracked: Any
_run_parallel_tick: Any
_run_sequential_tick: Any
_run_verify_commands: Any
_sanitize_branch_segment: Any
_sanitize_slug: Any
_squash_and_force_push: Any
_stderr_log_tail: Any
_stranded_fix_unpushed: Any
_sweep_community_contribution_prs: Any
_sync_pr_worktree_to_base: Any
_sync_worktree_with_base: Any
_try_recover_validating_transient_park: Any
_with_orch_marker: Any
_worktree_dirty_files: Any
_worktree_path: Any
subprocess: Any
tick: Any
__all__: tuple[str, ...]
