# Copyright 2026 Geser Dugarov
# SPDX-License-Identifier: Apache-2.0
"""Implementing publication."""
from __future__ import annotations

from orchestrator.stages import _implement_state as _state
from orchestrator.stages import implementing as _owner

_PRWork = _owner._PRWork
AgentResult = _owner.AgentResult
GitHubClient = _owner.GitHubClient
Issue = _owner.Issue
Path = _owner.Path
PinnedState = _owner.PinnedState
WorkflowLabel = _owner.WorkflowLabel
config = _owner.config
_AGENT_TIMEOUT = _state._AGENT_TIMEOUT
_BRANCH = _state._BRANCH
_IMPLEMENTING_STAGE = _state._IMPLEMENTING_STAGE
_PARK_REASON = _state._PARK_REASON
_PRE_IMPLEMENT_SHA = _state._PRE_IMPLEMENT_SHA
_PR_BODY_AGENT_MESSAGE_CAP = _state._PR_BODY_AGENT_MESSAGE_CAP
_PR_BODY_TRUNCATION_MARKER = _state._PR_BODY_TRUNCATION_MARKER
_RETRY_COUNT = _state._RETRY_COUNT
_RETRY_WINDOW_START = _state._RETRY_WINDOW_START
_SILENT_PARK_COUNT = _state._SILENT_PARK_COUNT


def _format_pr_agent_message(
    message: str, *, cap: int = _PR_BODY_AGENT_MESSAGE_CAP
) -> str:
    """Return the agent's final message ready to embed in a PR body.

    A message within `cap` is returned verbatim. A longer one is trimmed on the
    nearest paragraph -> line -> word boundary before `cap` and an explicit
    `_…(message truncated)_` marker is appended, so the PR body reads as
    intentionally clipped rather than severed mid-sentence. A dangling code
    fence in the trimmed region is closed first so the marker (and any following
    body) renders outside the half-open block instead of being swallowed by it.
    """
    if len(message) <= cap:
        return message
    head = message[:cap]
    # Prefer a paragraph break, then a line break, then a word boundary, so the
    # cut lands somewhere readable instead of mid-token.
    for sep in ("\n\n", "\n", " "):
        idx = head.rfind(sep)
        if idx > 0:
            head = head[:idx]
            break
    head = head.rstrip()
    # An odd count of ``` fences means the cut landed inside a fenced block;
    # close it so GitHub doesn't swallow the marker into the open code block.
    if head.count("```") % 2:
        head = f"{head}\n```"
    return f"{head}\n\n{_PR_BODY_TRUNCATION_MARKER}"


def _derive_pr_title(spec: config.RepoSpec, issue: Issue, wt: Path) -> str:
    """PR title for a freshly opened dev PR.

    Prefers the first commit's conventional subject; when that carries no
    recognizable `<type>:` prefix, one is inferred from recent base-branch
    history (`_infer_subject_prefix`) and applied to the issue title.
    """
    from orchestrator import workflow as _wf

    first_subject = _wf._first_commit_subject(spec, wt)
    fallback_prefix = _wf._infer_subject_prefix(spec, wt, issue)
    return _wf._pr_title_from_commit_or_issue(
        issue, first_subject, fallback_prefix,
    )


def _build_pr_body(
    state: PinnedState, issue: Issue, agent_result: AgentResult,
) -> str:
    """PR body: the `Resolves #N` line, the generating session's identity, and
    the (capped) final agent message when the run produced one."""
    _, dev_backend, _, dev_sid = _owner._read_dev_session(state)
    session_id = dev_sid or "?"
    body_parts = [
        f"Resolves #{issue.number}",
        "",
        f"Generated by orchestrator ({dev_backend} session `{session_id}`).",
    ]
    if agent_result.last_message.strip():
        body_parts += [
            "", "---", "_Last agent message:_", "",
            _owner._format_pr_agent_message(agent_result.last_message),
        ]
    return "\n".join(body_parts)


def _reuse_or_open_pr(
    gh: GitHubClient,
    spec: config.RepoSpec,
    issue: Issue,
    state: PinnedState,
    work: _PRWork,
):
    """Return the PR for `branch`, reusing an open one or opening a new one.

    Recovers gracefully if a previous tick crashed between `open_pr` and the
    relabel: an existing open PR is reused instead of 422-ing on a duplicate.
    Opening a new PR posts the ":sparkles: PR opened" comment and emits the
    `pr_opened` event; reuse only logs.
    """
    from orchestrator import workflow as _wf

    pr = gh.find_open_pr(branch=work.branch, base=spec.base_branch)
    if pr is not None:
        _wf.log.info(
            "issue=#%s reusing existing PR #%d for %s",
            issue.number, pr.number, work.branch,
        )
        return pr
    pr = gh.open_pr(
        branch=work.branch, base=spec.base_branch,
        title=_owner._derive_pr_title(spec, issue, work.worktree),
        body=_owner._build_pr_body(state, issue, work.agent_result),
    )
    _wf._post_issue_comment(gh, issue, state, f":sparkles: PR opened: #{pr.number}")
    gh.emit_event(
        "pr_opened",
        issue_number=issue.number,
        stage=_IMPLEMENTING_STAGE,
        pr_number=pr.number,
        branch=work.branch,
        sha=getattr(pr.head, "sha", None) or None,
        retry_count=state.get(_RETRY_COUNT),
    )
    return pr


def _advance_to_validating(
    gh: GitHubClient, issue: Issue, state: PinnedState, pr, branch: str
) -> None:
    """Record the published PR/branch, reset the per-PR budgets, and hand off
    to `validating`.

    The docs pass runs only as the final-docs handoff after the reviewer agent
    approves, so a fresh commit goes straight to validating.
    """
    state.set("pr_number", pr.number)
    # Persist the pushed branch alongside `pr_number` so the next tick's
    # `_resolve_branch_name` can recover it directly. Without this, a state
    # that lacked `branch` going in (e.g. an awaiting-human resume that opened
    # the PR here without first passing through the fresh-spawn branch-persist
    # site) would leave `pr_number` set with `branch` unset; the legacy-PR
    # fallback in `_resolve_branch_name` would then misroute every downstream
    # tick to `orchestrator/issue-<n>` while the live PR is on the
    # slug-namespaced branch this push just published.
    state.set(_BRANCH, branch)
    _owner._reset_implementing_counters(state)
    gh.set_workflow_label(issue, WorkflowLabel.VALIDATING)


def _reset_implementing_counters(state: PinnedState) -> None:
    # Reset the review counter every time we (re-)open a PR so the validating
    # handler starts fresh on the new branch state.
    state.set("review_round", 0)
    # Issue moved forward; reset the implementing retry budget so any future
    # bounce back into implementing (e.g. validating -> implementing in a
    # later stage) starts with a fresh window.
    state.set(_RETRY_COUNT, 0)
    state.set(_RETRY_WINDOW_START, None)
    # The session just produced commits, so it isn't poisoned -- reset the
    # silent-park streak so a future blip doesn't tip an otherwise-healthy
    # session past the fresh-session threshold.
    state.set(_SILENT_PARK_COUNT, 0)
    # The commit shipped, so any agent-timeout park watermark is spent -- clear
    # it (and the stale reason) so it cannot linger into `validating` or
    # mis-fire the next-tick timeout recovery on a later implementing hop.
    if state.get(_PARK_REASON) == _AGENT_TIMEOUT:
        state.set(_PARK_REASON, None)
    state.set(_PRE_IMPLEMENT_SHA, None)


def _on_commits(
    gh: GitHubClient,
    spec: config.RepoSpec,
    issue: Issue,
    state: PinnedState,
    agent_result: AgentResult,
) -> None:
    from orchestrator import workflow as _wf

    wt = _wf._worktree_path(spec, issue.number)
    branch = _wf._resolve_branch_name(state, spec, issue.number)
    if not _wf._push_branch(spec, wt, branch):
        # Park on awaiting_human like the timeout/question paths. Otherwise the
        # worktree's commits keep _has_new_commits() true, so every poll would
        # re-enter _on_commits() and re-comment indefinitely until a human acts.
        _wf._park_awaiting_human(
            gh, issue, state,
            f"{config.HITL_MENTIONS} git push failed; see orchestrator logs.",
            reason="push_failed",
        )
        # _handle_implementing writes pinned state after we return.
        return
    pr = _owner._reuse_or_open_pr(
        gh, spec, issue, state, _PRWork(agent_result, wt, branch),
    )
    _owner._advance_to_validating(gh, issue, state, pr, branch)
